apiVersion: v1
kind: Service
metadata:
  name: bootcamp-nginx-svc
  namespace: muco
  labels:
    node: mucobaba 
spec:
  selector:
    app: bootcamp-nginx
  ports:
  - port: 80
    targetPort: 3000